WITH TERM AS (
  SELECT
    DISTINCT(TERMS.NAME),
    TERMS.FIRSTDAY TERM_FIRSTDAY,
    TERMS.LASTDAY  TERM_LASTDAY,
    TERMS.NAME     TERM_NAME,
    TERMS.YEARID   TERM_YEARID
  FROM
    TERMS
  WHERE
    REGEXP_LIKE(TERMS.NAME, '^[0-9]{4}-[0-9]{4}$')
    AND TERMS.YEARID = SUBSTR(EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE, -6)), -2) + 10
), EXCLUDED_STUDENTS AS (
  SELECT
    DISTINCT(STUDENTS.ID) EX_STUDENTID
  FROM
    STUDENTS
    JOIN TERMS
    ON TERMS.SCHOOLID = STUDENTS.SCHOOLID
  WHERE
    STUDENTS.EXITCODE IN ('1908', '1909', '3508', '1919', '1910', '1911', '1912', '1913', '1914', '1915', '1917', '3503', '1923', '3509', '1930', '3504', '1928')
    AND STUDENTS.ENTRYDATE >= (
      SELECT
        TERM.TERM_FIRSTDAY
      FROM
        TERM
    )
), SCHOOL AS (
  SELECT
    SCHOOLS.SCHOOL_NUMBER           SCHOOL_ID,
    SCHOOLS.NAME                    SCHOOL_NAME,
    SCHOOLS.SCHOOLCATEGORYCODESETID
  FROM
    SCHOOLS
  WHERE
    SCHOOLS.SCHOOLCATEGORYCODESETID IN (35201, 35202, 35203)
), T_TPS_GRAD_ICAP AS (
  SELECT
    STUDENTSDCID,
    LOWER(TRIM(TPS_GRAD_ICAP9))    ICAP_09,
    LOWER(TRIM(TPS_GRAD_ICAP10))   ICAP_10,
    LOWER(TRIM(TPS_GRAD_ICAP11))   ICAP_11,
    LOWER(TRIM(TPS_GRAD_ICAP12))   ICAP_12,
    LOWER(TRIM(TPS_GRAD_ICAP_WBL)) ICAP_WBL
  FROM
    U_STUDENTSUSERFIELDS
), STUDENT AS (
  SELECT
    STUDENTS.ID                        STUDENT_ID,
    STUDENTS.DCID,
    STUDENTS.STUDENT_NUMBER,
    STUDENTS.STATE_STUDENTNUMBER,
    STUDENTS.LASTFIRST,
    STUDENTS.FIRST_NAME,
    STUDENTS.MIDDLE_NAME,
    STUDENTS.LAST_NAME,
    STUDENTS.ENROLL_STATUS,
    STUDENTS.GRADE_LEVEL,
    STUDENTS.SCHED_YEAROFGRADUATION    COHORT,
    USF.TPS_GRADUATION_COUNSELOR       COUNSELOR,
    USF.TPS_GRADUATION_PROGRESS_OHLA02 OK_PROMISE_REGISTERED,
    LOWER(TRIM(USF.TPS_GRAD_ICAP9))    ICAP_09,
    LOWER(TRIM(USF.TPS_GRAD_ICAP10))   ICAP_10,
    LOWER(TRIM(USF.TPS_GRAD_ICAP11))   ICAP_11,
    LOWER(TRIM(USF.TPS_GRAD_ICAP12))   ICAP_12,
    LOWER(TRIM(USF.TPS_GRAD_ICAP_WBL)) ICAP_WBL,
    (
      SELECT
        CASE
          WHEN 'exempt' IN (ICAP_09, ICAP_10, ICAP_11, ICAP_12, ICAP_WBL) THEN
            'Exempt'
          WHEN 'yes' = ALL (ICAP_09, ICAP_10, ICAP_11, ICAP_12, ICAP_WBL) THEN
            'Yes'
          ELSE
            'No'
        END
      FROM
        T_TPS_GRAD_ICAP
      WHERE
        T_TPS_GRAD_ICAP.STUDENTSDCID = STUDENTS.DCID
    ) ICAP_COMBINED,
    USF.TPS_GRAD_FLP FINANCIAL_LITERACY,
    USF.TPS_GRAD_CPR CPR,
    USF.TPS_GRADUATION_PROGRESS GRADUATION_PROGRESS,
    USF.TPS_GRAD_INDUSTRY INDUSTRY_ENDORSEMENT,
    USF.TPS_GRADUATION_PROGRESS_OK_A01 OK_ACADEMIC_SCHOLAR,
    USF.TPS_GRAD_TULSABEYOND TULSA_BEYOND,
    USF.TPS_GRADUATION_PROGRESS_AP AP_SCHOLARS,
    USF.TPS_GRADUATION_PROGRESS_OHLA01 OK_PROMISE_RECEIVED,
    USF.TPS_GRADUATION_PROGRESS_IB IB_RECEIVED_BTW_ONLY,
    USF.TPS_GRADUATION_PROGRESS_AP_D01 AP_DIPLOMA_EDISON_ONLY,
    USF.TPS_GRAD_OSTP OSTP,
    USF.TPS_GRAD_ACE ACE
  FROM
    STUDENTS
    JOIN U_STUDENTSUSERFIELDS USF
    ON STUDENTS.DCID = USF.STUDENTSDCID
)
SELECT
  ID,
  STUDENT_NUMBER,
  STATE_STUDENTNUMBER,
  LASTFIRST,
  FIRST_NAME,
  MIDDLE_NAME,
  LAST_NAME,
  ENROLL_STATUS,
  GRADE_LEVEL,
  COHORT,
  COUNSELOR,
  OK_PROMISE_REGISTERED,
  ICAP_09,
  ICAP_10,
  ICAP_11,
  ICAP_12,
  ICAP_WBL,
  ICAP_COMBINED,
  FINANCIAL_LITERACY,
  CPR,
  GRADUATION_PROGRESS,
  INDUSTRY_ENDORSEMENT,
  OK_ACADEMIC_SCHOLAR,
  TULSA_BEYOND,
  OK_PROMISE_RECEIVED,
  IB_RECEIVED_BTW_ONLY,
  AP_DIPLOMA_EDISON_ONLY,
  OSTP,
  ACE,
  ENTRY_DATE,
  EXIT_DATE,
  EXIT_CODE,
  EXIT_COMMENT,
  SCHOOL_ID,
  PC_ENROLLMENT,
  EXIT_CODE_STATUS
FROM
  (
    SELECT
      STUDENTS.ID,
      STUDENTS.ENTRYDATE                                  ENTRY_DATE,
      STUDENTS.EXITDATE                                   EXIT_DATE,
      STUDENTS.EXITCODE                                   EXIT_CODE,
      DBMS_LOB.SUBSTR(STUDENTS.EXITCOMMENT, 4000, 1)      EXIT_COMMENT,
      SCHOOL.SCHOOL_ID                                    SCHOOL_ID,
      SCHOOL.SCHOOL_NAME                                  SCHOOL_NAME,
      'Current Enrollment'                                PC_ENROLLMENT,
      'Good Exit Code'                                    EXIT_CODE_STATUS
    FROM
      STUDENTS
      JOIN SCHOOL
      ON SCHOOL.SCHOOL_ID = STUDENTS.SCHOOLID
    WHERE
      STUDENTS.ENTRYDATE >= (
        SELECT
          TERM.TERM_FIRSTDAY
        FROM
          TERM
      )
      AND STUDENTS.EXITDATE < (
        SELECT
          TERM.TERM_LASTDAY
        FROM
          TERM
      )
      AND STUDENTS.ID NOT IN (
        SELECT
          EXCLUDED_STUDENTS.EX_STUDENTID
        FROM
          EXCLUDED_STUDENTS
      )
    UNION
    SELECT
      STUDENTS.ID,
      REENROLLMENTS.ENTRYDATE                             ENTRY_DATE,
      REENROLLMENTS.EXITDATE                              EXIT_DATE,
      REENROLLMENTS.EXITCODE                              EXIT_CODE,
      DBMS_LOB.SUBSTR(REENROLLMENTS.EXITCOMMENT, 4000, 1) EXIT_COMMENT,
      REENROLLMENTS.SCHOOLID                              SCHOOL_ID,
      SCHOOL.SCHOOL_NAME                                  SCHOOL_NAME,
      'Previous Enrollment'                               PC_ENROLLMENT,
      CASE
        WHEN REENROLLMENTS.EXITCODE IN ('1927', '1925', '1926', '1918', '1916', '1907', '3505', '1921') THEN
          'Correct Exit Code'
        WHEN REENROLLMENTS.EXITCODE NOT IN ('1927', '1925', '1926', '1918', '1916', '1907', '3505', '1921') THEN
          'Check Exit Code'
      END                                                 EXIT_CODE_STATUS
    FROM
      REENROLLMENTS
      JOIN STUDENTS
      ON REENROLLMENTS.STUDENTID = STUDENTS.ID JOIN SCHOOL
      ON REENROLLMENTS.SCHOOLID = SCHOOL.SCHOOL_ID
    WHERE
      REENROLLMENTS.ENTRYDATE != REENROLLMENTS.EXITDATE
      AND REENROLLMENTS.ENTRYDATE >= (
        SELECT
          TERM.TERM_FIRSTDAY
        FROM
          TERM
      )
      AND REENROLLMENTS.EXITDATE = (
        SELECT
          MAX(RE.EXITDATE)
        FROM
          REENROLLMENTS RE
        WHERE
          RE.STUDENTID = REENROLLMENTS.STUDENTID
          AND RE.EXITDATE != RE.ENTRYDATE
      )
      AND REGEXP_LIKE(REENROLLMENTS.EXITCODE, '[0-9]{4}')
      AND REENROLLMENTS.EXITDATE <= TRUNC(SYSDATE)
      AND STUDENTS.ENROLL_STATUS != 0
      AND STUDENTS.ENTRYDATE = STUDENTS.EXITDATE
    UNION
    SELECT
      STUDENTS.ID                                         ID,
      STUDENTS.ENTRYDATE                                  ENTRY_DATE,
      STUDENTS.EXITDATE                                   EXIT_DATE,
      STUDENTS.EXITCODE                                   EXIT_CODE,
      DBMS_LOB.SUBSTR(STUDENTS.EXITCOMMENT, 4000, 1)      EXIT_COMMENT,
      SCHOOL.SCHOOL_ID                                    SCHOOL_ID,
      SCHOOL.SCHOOL_NAME                                  SCHOOL_NAME,
      'Active Enrollment'                                 PC_ENROLLMENT,
      'Good Exit Code'                                    EXIT_CODE_STATUS
    FROM
      STUDENTS
      JOIN SCHOOL
      ON SCHOOL.SCHOOL_ID = STUDENTS.SCHOOLID
    WHERE
      STUDENTS.EXITDATE = (
        SELECT
          TERM.TERM_LASTDAY
        FROM
          TERM
      ) + 1
  )                 
  JOIN STUDENT
  ON ID = STUDENT.STUDENT_ID