SELECT
  A.ID,
  A.STUDENT_NUMBER,
  A.FIRST_NAME,
  A.MIDDLE_NAME,
  A.LAST_NAME,
  A.LASTFIRST,
  A.ENROLL_STATUS,
  A.ETHNICITY,
  A.GRADE_LEVEL,
  A.HOME_ROOM,
  A.GENDER,
  A.LUNCHSTATUS,
  A.TEAM,
  A.HOUSE,
  A.BUILDING,
  A.GEOCODE,
  B.NAME                 AS "SCHOOL",
  (
    SELECT
      LISTAGG (RACECD,
      ', ') WITHIN GROUP (ORDER BY RACECD)
    FROM
      STUDENTRACE A2
    WHERE
      A2.STUDENTID = A.ID
  ) AS "RACE",
 --
  F.INCIDENT_ID AS "INCIDENT_ID",
  F.INCIDENT_TS AS "INCIDENT_DATE",
 --
  (
    SELECT
      W2.INCIDENT_CATEGORY
    FROM
      INCIDENT_DETAIL  W1, -- incloc
      INCIDENT_LU_CODE W2 -- incluc
    WHERE
      W1.LU_CODE_ID = W2.LU_CODE_ID
      AND F.INCIDENT_ID = W1.INCIDENT_ID
      AND W2.CODE_TYPE = 'locationcode'
  ) AS "LOCATION",
 --
  F.ENTRY_AUTHOR AS "REFERRED_BY",
  K.SUB_CATEGORY AS "ACTION",
  L.ACTION_PLAN_BEGIN_DT AS "ACTION_PLAN_BEGIN_DATE",
  (
    SELECT
      X2.SUB_CATEGORY
    FROM
      INCIDENT_DETAIL      X1, --incdur,
      INCIDENT_LU_SUB_CODE X2 --incsuact
    WHERE
      L.DURATION_INCIDENT_DETAIL_ID = X1.INCIDENT_DETAIL_ID
      AND X1.LU_SUB_CODE_ID = X2.LU_SUB_CODE_ID
  ) AS "SUB_CATEGORY",
  L.ACTION_PLAN_END_DT AS "ACTION_PLAN_END_DATE",
  CASE
    WHEN L.ACTION_PLAN_END_DT - L.ACTION_PLAN_BEGIN_DT = 0 THEN
      1
    WHEN L.ACTION_PLAN_END_DT - L.ACTION_PLAN_BEGIN_DT > 0 THEN
      L.ACTION_PLAN_END_DT - L.ACTION_PLAN_BEGIN_DT
  END AS "ACTION_DURATION"
 --
FROM
  SCHOOLS              B,
  FTE                  Z,
  STUDENTS             A,
 --
  INCIDENT_PERSON_ROLE E, --ipr
  INCIDENT             F, --inc
  INCIDENT_PERSON_ROLE G, --incpr
  INCIDENT_DETAIL      H, --incd
  INCIDENT_DETAIL      J, --incbehav
  INCIDENT_LU_SUB_CODE K, --incsu
  INCIDENT_ACTION      L --inact
WHERE
  B.SCHOOL_NUMBER = A.SCHOOLID
  AND Z.ID = A.FTEID
 --
  AND A.ID = E.STUDENTID
  AND E.INCIDENT_ID = F.INCIDENT_ID
  AND A.ID = G.STUDENTID
  AND F.INCIDENT_ID = G.INCIDENT_ID
  AND G.ROLE_INCIDENT_DETAIL_ID = H.INCIDENT_DETAIL_ID
  AND H.LU_CODE_ID IN (
    SELECT
      LU_CODE_ID
    FROM
      INCIDENT_LU_CODE
    WHERE
      INCIDENT_CATEGORY = 'Offender'
  )
  AND F.INCIDENT_ID = J.INCIDENT_ID
  AND J.LU_SUB_CODE_ID = K.LU_SUB_CODE_ID
  AND J.INCIDENT_DETAIL_ID = L.ACTION_INCIDENT_DETAIL_ID